### ISSUE TITLE
The TileMap node is deprecated as it is superseded by the use of multiple TileMapLayer nodes.

### ISSUE THREAD

**Issue by bukowa** [Maaack/Sprout-Lands-Tilemap#1]
![a22ace11a34a3c1e9e7a8c52e9d2446b](https://github.com/user-attachments/assets/cf61b3d3-1700-4d9c-9d4e-5f0b087f61cb)

**Comment by Maaack** [comment]
Thanks for reporting the issue. I hope to update this in the near future.
